// Generates src/lib/zineArrangerData.ts from scripts/templates.json + ground-truth.json
// (gridType per variant is taken from the ground-truth sheet classes).
import { readFileSync, writeFileSync } from 'node:fs'

const ROOT = 'C:/Users/Gabriel/Documents/kimi/workspace/zine-studio'
const templates = JSON.parse(readFileSync(`${ROOT}/scripts/templates.json`, 'utf8'))
const truth = JSON.parse(readFileSync(`${ROOT}/scripts/ground-truth.json`, 'utf8'))

for (const key of Object.keys(templates)) {
  const t = templates[key]
  const g = truth[key]
  if (!g) {
    // half has no 'top' variants; ensure key exists for all
    console.error(`missing ground truth for ${key}`)
    process.exit(1)
  }
  const first = Object.values(g)[0]
  let gridType = first.sheets[0].sheetClass.split(' ')[0]
  // Quarter single-sided omits the grid class in the reference, falling back to
  // the default .zine-sheet grid ("tl tr" / "bl br") — identical to qtr-side.
  if (gridType === 'guide-margins' || gridType === '') gridType = 'qtr-side'
  t.grid = gridType
  if (t.k == null) t.k = t.loopBound / 2
}

const header = `/**
 * Imposition layout data ported from Zine Arranger.
 *
 * Zine Arranger
 * Copyright (c) 2024 Nash High
 * Licensed under the MIT License — see LICENSE-zine-arranger.txt
 *
 * This file is GENERATED by scripts/extract-templates.mjs, which executes the
 * reference implementation's sheet-layout loops with symbolic page variables
 * and records the resulting cell templates verbatim. Do not hand-edit.
 */

export type EdgeLetter = 't' | 'b' | 'l' | 'r'
export type PageBase = 's' | 'e' | 'm' | 'n'

export interface CellTemplate {
  /** Grid area name (tl/tr/.../gRC). */
  area: string
  base: PageBase
  offset: number
  /** Quarter "two copies" mode: second copy of the same page. */
  copy: boolean
  /** Rotate cell contents 180 degrees. */
  rotate: boolean
  /** Cut guides (solid when Center guides on). */
  cuts: EdgeLetter[]
  /** Fold guides (dotted). */
  folds: EdgeLetter[]
  /** Alternate treatment when this cell holds the back cover of a top-fold zine and flipBackCover is off. */
  bcAlt?: { rotate: boolean; cuts: EdgeLetter[]; folds: EdgeLetter[] }
}

export interface SheetTemplate {
  sheetInIter: number
  cells: CellTemplate[]
}

export interface VariantTemplate {
  /** Pages per sheet of paper (front+back for duplex). */
  loopBound: number
  /** Step of the s counter per sheet pair. */
  k: number
  /** Whether the m/n middle variables are used (quarter regular duplex). */
  useMN: boolean
  sheetsPerIter: number
  /** CSS grid class from the reference (half-por, qtr-side, eig-lnd, twlv-por, ...). */
  grid: string
  sheets: SheetTemplate[]
}

export const VARIANT_TEMPLATES: Record<string, VariantTemplate> = `

const body = JSON.stringify(templates, null, 1)

writeFileSync(`${ROOT}/src/lib/zineArrangerData.ts`, header + body + '\n')
console.log('Wrote src/lib/zineArrangerData.ts')
